name: Tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  schedule:
    - cron: "15 7 */9 * *"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    strategy:
      matrix:
        python-version: ["310", "311", "312", "313", "314", "314t"]
        runner: [ubuntu-slim]
        include:
          - python-version: "314"
            runner: macos-latest
          - python-version: "314"
            runner: windows-latest
          - python-version: "314"
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: boidolr/actions/run-tox@d87fde10d5386f84f4ac1cd9b6becb61b7b892fe # main
        with:
          python-version: ${{ matrix.python-version }}

  precommit:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: boidolr/actions/run-precommit@d87fde10d5386f84f4ac1cd9b6becb61b7b892fe # main
        env:
          UV_PYTHON: "3.14"
