name: Publish release
on:
  push:
    tags: ["v**"]

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-slim
    if: github.actor == 'boidolr'

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Create release for tag
        run: |
          TAG=$(echo "${GITHUB_REF}" | cut -c 11-)
          gh release create --verify-tag --generate-notes "$TAG"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
