name: Publish release
on:
  push:
    tags: ["v**"]

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-slim
    if: github.actor == 'boidolr'

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Create release for tag
        run: |
          TAG=$(echo "${GITHUB_REF}" | cut -c 11-)
          gh release create --verify-tag --generate-notes "$TAG"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
